/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtworksRouteImport } from './routes/artworks'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksRoute = ArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artworks': typeof ArtworksRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/export': typeof ExportRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artworks': typeof ArtworksRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/export': typeof ExportRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/artworks': typeof ArtworksRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/export': typeof ExportRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artworks'
    | '/auth'
    | '/community'
    | '/exhibitions'
    | '/export'
    | '/admin'
    | '/email/unsubscribe'
    | '/api/public/setup-admin'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artworks'
    | '/auth'
    | '/community'
    | '/exhibitions'
    | '/export'
    | '/admin'
    | '/email/unsubscribe'
    | '/api/public/setup-admin'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/artworks'
    | '/auth'
    | '/community'
    | '/exhibitions'
    | '/export'
    | '/_authenticated/admin'
    | '/email/unsubscribe'
    | '/api/public/setup-admin'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArtworksRoute: typeof ArtworksRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ExhibitionsRoute: typeof ExhibitionsRoute
  ExportRoute: typeof ExportRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks': {
      id: '/artworks'
      path: '/artworks'
      fullPath: '/artworks'
      preLoaderRoute: typeof ArtworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArtworksRoute: ArtworksRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ExhibitionsRoute: ExhibitionsRoute,
  ExportRoute: ExportRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
