/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ExportRouteImport } from './routes/export'
import { Route as ExhibitionsRouteImport } from './routes/exhibitions'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtworksRouteImport } from './routes/artworks'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin.subscribers'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin.inventory'
import { Route as AuthenticatedAdminExhibitionsRouteImport } from './routes/_authenticated/admin.exhibitions'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAdminOrdersOrderIdRouteImport } from './routes/_authenticated/admin.orders.$orderId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitionsRoute = ExhibitionsRouteImport.update({
  id: '/exhibitions',
  path: '/exhibitions',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksRoute = ArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExhibitionsRoute =
  AuthenticatedAdminExhibitionsRouteImport.update({
    id: '/exhibitions',
    path: '/exhibitions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminOrdersOrderIdRoute =
  AuthenticatedAdminOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artworks': typeof ArtworksRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/export': typeof ExportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/exhibitions': typeof AuthenticatedAdminExhibitionsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artworks': typeof ArtworksRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/export': typeof ExportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/exhibitions': typeof AuthenticatedAdminExhibitionsRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/artworks': typeof ArtworksRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/exhibitions': typeof ExhibitionsRoute
  '/export': typeof ExportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/exhibitions': typeof AuthenticatedAdminExhibitionsRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/orders/$orderId': typeof AuthenticatedAdminOrdersOrderIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artworks'
    | '/auth'
    | '/checkout'
    | '/community'
    | '/events'
    | '/exhibitions'
    | '/export'
    | '/reset-password'
    | '/robots.txt'
    | '/unsubscribe'
    | '/account'
    | '/admin'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/orders/$orderId'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/exhibitions'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/api/public/setup-admin'
    | '/lovable/email/suppression'
    | '/admin/orders/$orderId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artworks'
    | '/auth'
    | '/checkout'
    | '/community'
    | '/events'
    | '/exhibitions'
    | '/export'
    | '/reset-password'
    | '/robots.txt'
    | '/unsubscribe'
    | '/account'
    | '/admin'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/orders/$orderId'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/events'
    | '/admin/exhibitions'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/api/public/setup-admin'
    | '/lovable/email/suppression'
    | '/admin/orders/$orderId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/artworks'
    | '/auth'
    | '/checkout'
    | '/community'
    | '/events'
    | '/exhibitions'
    | '/export'
    | '/reset-password'
    | '/robots.txt'
    | '/unsubscribe'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/orders/$orderId'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/exhibitions'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subscribers'
    | '/api/public/setup-admin'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/orders/$orderId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ArtworksRoute: typeof ArtworksRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  ExhibitionsRoute: typeof ExhibitionsRoute
  ExportRoute: typeof ExportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibitions': {
      id: '/exhibitions'
      path: '/exhibitions'
      fullPath: '/exhibitions'
      preLoaderRoute: typeof ExhibitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks': {
      id: '/artworks'
      path: '/artworks'
      fullPath: '/artworks'
      preLoaderRoute: typeof ArtworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exhibitions': {
      id: '/_authenticated/admin/exhibitions'
      path: '/exhibitions'
      fullPath: '/admin/exhibitions'
      preLoaderRoute: typeof AuthenticatedAdminExhibitionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/orders/$orderId': {
      id: '/_authenticated/admin/orders/$orderId'
      path: '/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedAdminOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
  }
}

interface AuthenticatedAdminOrdersRouteChildren {
  AuthenticatedAdminOrdersOrderIdRoute: typeof AuthenticatedAdminOrdersOrderIdRoute
}

const AuthenticatedAdminOrdersRouteChildren: AuthenticatedAdminOrdersRouteChildren =
  {
    AuthenticatedAdminOrdersOrderIdRoute: AuthenticatedAdminOrdersOrderIdRoute,
  }

const AuthenticatedAdminOrdersRouteWithChildren =
  AuthenticatedAdminOrdersRoute._addFileChildren(
    AuthenticatedAdminOrdersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminExhibitionsRoute: typeof AuthenticatedAdminExhibitionsRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminExhibitionsRoute: AuthenticatedAdminExhibitionsRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ArtworksRoute: ArtworksRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  ExhibitionsRoute: ExhibitionsRoute,
  ExportRoute: ExportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
